name: My CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Use the DATABASE_URL secret
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo $DATABASE_URL
        # You can use the DATABASE_URL in your commands or scripts here
